const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const { supabase } = require('../db');
const { authenticateJWT } = require('./auth');

const sessionMetaPath = path.join(__dirname, '../data/session_meta.json');
function saveLocalSessionMeta(type, id, subject, division) {
  try {
    let meta = {};
    if (fs.existsSync(sessionMetaPath)) {
      try { meta = JSON.parse(fs.readFileSync(sessionMetaPath, 'utf8')); } catch(e) {}
    }
    meta[`${type}_${id}`] = {
      subject: subject || null,
      division: division || null,
      updated_at: new Date().toISOString()
    };
    if (!fs.existsSync(path.dirname(sessionMetaPath))) fs.mkdirSync(path.dirname(sessionMetaPath), { recursive: true });
    fs.writeFileSync(sessionMetaPath, JSON.stringify(meta, null, 2), 'utf8');
  } catch (e) {
    console.error('Error saving local session meta:', e);
  }
}

// Middleware to restrict to admins or faculty
const requireAdmin = (req, res, next) => {
  if (req.user && (req.user.role === 'admin' || req.user.role === 'faculty')) {
    next();
  } else {
    res.status(403).json({ error: 'Access denied. Admins or Faculty only' });
  }
};

// Get today's local date string (YYYY-MM-DD)
function getLocalDateString() {
  const d = new Date();
  // Adjust for local timezone offset
  const offset = d.getTimezoneOffset();
  const localD = new Date(d.getTime() - (offset * 60 * 1000));
  return localD.toISOString().split('T')[0];
}

// GET today's OTP history and current remaining counts
router.get('/today', authenticateJWT, requireAdmin, async (req, res) => {
  try {
    const today = getLocalDateString();
    
    // Select OTPs generated by this faculty member today
    const { data: otps, error } = await supabase.from('otp')
      .select('*')
      .eq('generated_by', req.user.id)
      .eq('date', today);

    if (error) throw error;

    const count = otps ? otps.length : 0;
    const remaining = Math.max(0, 5 - count);

    res.json({
      todayCount: count,
      remaining,
      otps: otps || []
    });
  } catch (err) {
    console.error('Error fetching today OTPs:', err);
    res.status(500).json({ error: 'Failed to fetch OTP status' });
  }
});

// GET currently active OTP session (if valid and not expired)
router.get('/active', authenticateJWT, requireAdmin, async (req, res) => {
  try {
    const nowMs = Date.now();
    const { data: activeOtps, error } = await supabase.from('otp')
      .select('*')
      .eq('generated_by', req.user.id)
      .order('id', { ascending: false })
      .limit(5);

    if (error) throw error;

    let activeSession = null;
    let secondsLeft = 0;

    if (activeOtps && activeOtps.length > 0) {
      for (const sess of activeOtps) {
        const expireTime = new Date(sess.expire_time).getTime();
        if (nowMs < expireTime) {
          activeSession = sess;
          secondsLeft = Math.max(0, Math.floor((expireTime - nowMs) / 1000));
          break;
        }
      }
    }

    if (activeSession) {
      res.json({
        active: true,
        otp: activeSession.otp,
        expireTime: activeSession.expire_time,
        secondsLeft,
        semester: activeSession.semester || null,
        division: activeSession.division || null
      });
    } else {
      res.json({ active: false });
    }
  } catch (err) {
    console.error('Error checking active OTP:', err);
    res.status(500).json({ error: 'Failed to check active OTP' });
  }
});

// POST generate a new OTP (Faculty only, max 5 per day)
router.post('/generate', authenticateJWT, requireAdmin, async (req, res) => {
  try {
    const today = getLocalDateString();
    const { semester, division, subject } = req.body;

    // Check 5 daily limit per faculty
    const { data: todayOtps, error: countErr } = await supabase.from('otp')
      .select('id')
      .eq('generated_by', req.user.id)
      .eq('date', today);

    if (countErr) throw countErr;

    if (todayOtps && todayOtps.length >= 5) {
      return res.status(403).json({ error: 'Daily limit reached. You can generate a maximum of 5 OTPs per day.' });
    }

    // Generate random 6-digit OTP code
    const otpCode = Math.floor(100000 + Math.random() * 900000).toString();
    const now = new Date();
    const generatedTime = now.toISOString();
    const expireTime = new Date(now.getTime() + 2 * 60 * 1000).toISOString();

    let insertPayload = {
      otp: otpCode,
      generated_time: generatedTime,
      expire_time: expireTime,
      generated_by: req.user.id,
      date: today,
      semester: semester ? parseInt(semester) : null,
      division: (division && String(division).trim() !== '') ? String(division).trim().toUpperCase() : null,
      subject: (subject && String(subject).trim() !== '') ? String(subject).trim() : null
    };

    let { data: result, error } = await supabase.from('otp').insert([insertPayload]).select().single();
    
    // Fallback: If DB table lacks 'subject' or 'division' columns, retry without missing column and save local meta
    if (error && error.message && (error.message.includes('subject') || error.message.includes('division') || error.message.includes('schema cache'))) {
      if (error.message.includes('subject')) delete insertPayload.subject;
      if (error.message.includes('division')) delete insertPayload.division;

      const retry = await supabase.from('otp').insert([insertPayload]).select().single();
      result = retry.data;
      error = retry.error;
    }
    
    if (error) {
      console.error('OTP Insert Error:', error);
      return res.status(500).json({ error: 'Failed to generate OTP: ' + error.message });
    }

    if (result && result.id) {
      saveLocalSessionMeta('otp', result.id, subject, division);
    }

    res.status(201).json({
      message: 'OTP generated successfully',
      otp: {
        id: result.id,
        otp: otpCode,
        generatedTime,
        expireTime,
        secondsLeft: 120,
        semester: result.semester || semester || null,
        division: result.division || division || null,
        subject: result.subject || subject || null
      }
    });
  } catch (err) {
    console.error('Error generating OTP:', err);
    res.status(500).json({ error: 'Failed to generate OTP' });
  }
});

module.exports = router;
